services:

  odoo:
    image: odoo:18
    restart: always
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:8069:8069"
      - "127.0.0.1:8072:8072"
    volumes:
      - data:/var/lib/odoo

  postgres:
    image: postgres:17.2
    restart: always
    env_file: .env
    volumes:
      - db:/var/lib/postgresql/data/pgdata

volumes:
  data:
  db:
