services:

  postgres:
    image: postgres:17.2
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  odoo:
    image: odoo:18
    restart: always
    env_file:
      - ./.env
    depends_on:
      - postgres
    ports:
      - "8169:8069"
      - "8172:8072"
    environment:
      HOST: ${ODOO_DB_HOST}
      USER: ${POSTGRES_USER}
      PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./addons:/mnt/extra-addons
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
  